; version.asm
;
; Auto-generated by ZXVersion.exe
; On 16 Nov 2018 at 19:51

BuildNo                 macro()
                        db "111"
mend

BuildNoValue            equ "111"
BuildNoWidth            equ 0 + FW1 + FW1 + FW1



BuildDate               macro()
                        db "16 Nov 2018"
mend

BuildDateValue          equ "16 Nov 2018"
BuildDateWidth          equ 0 + FW1 + FW6 + FWSpace + FWN + FWo + FWv + FWSpace + FW2 + FW0 + FW1 + FW8



BuildTime               macro()
                        db "19:51"
mend

BuildTimeValue          equ "19:51"
BuildTimeWidth          equ 0 + FW1 + FW9 + FWColon + FW5 + FW1



BuildTimeSecs           macro()
                        db "19:51:00"
mend

BuildTimeSecsValue      equ "19:51:00"
BuildTimeSecsWidth      equ 0 + FW1 + FW9 + FWColon + FW5 + FW1 + FWColon + FW0 + FW0
