; version.asm
;
; Auto-generated by ZXVersion.exe
; On 01 Dec 2018 at 17:13

BuildNo                 macro()
                        db "137"
mend

BuildNoValue            equ "137"
BuildNoWidth            equ 0 + FW1 + FW3 + FW7



BuildDate               macro()
                        db "01 Dec 2018"
mend

BuildDateValue          equ "01 Dec 2018"
BuildDateWidth          equ 0 + FW0 + FW1 + FWSpace + FWD + FWe + FWc + FWSpace + FW2 + FW0 + FW1 + FW8



BuildTime               macro()
                        db "17:13"
mend

BuildTimeValue          equ "17:13"
BuildTimeWidth          equ 0 + FW1 + FW7 + FWColon + FW1 + FW3



BuildTimeSecs           macro()
                        db "17:13:40"
mend

BuildTimeSecsValue      equ "17:13:40"
BuildTimeSecsWidth      equ 0 + FW1 + FW7 + FWColon + FW1 + FW3 + FWColon + FW4 + FW0
